name: Build and release
on:
  push:
    branches:
      - '**'
       
env:
  native_image_opts: --verbose --enable-http --enable-https --initialize-at-build-time=org.codehaus.stax2.typed.Base64Variants
#  native_image_opts: --verbose --initialize-at-build-time=org.apache.logging.slf4j.Log4jLogger,org.apache.logging.log4j.spi.AbstractLogger,org.apache.logging.log4j.core.Logger,org.apache.logging.log4j.Level,org.apache.logging.slf4j.Log4jLoggerFactory
          
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          path: build/libs/fcli.jar

  native_linux:
    name: native-image-linux
    #if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '21.2.0.java11'

      - name: Install GraalVM's native-image extension
        run: gu install native-image

      - uses: actions/download-artifact@v2
        with:
          path: ./

      - name: Create native fcli
        run: mkdir -p native-image/linux && native-image ${{ env.native_image_opts }} -jar ./artifact/fcli.jar native-image/linux/fcli
        
      - name: Compress native fcli
        uses: svenstaro/upx-action@v2
        with:
          file: native-image/linux/fcli
        
      - name: Basic test of native fcli
        run: ./native-image/linux/fcli --help && ./native-image/linux/fcli get --help

      - uses: actions/upload-artifact@v2
        with:
          path: ./native-image
          
  native_mac:
    name: native-image-mac
    needs: build
    runs-on: macos-10.15
    steps:
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '21.2.0.java11'

      - name: Install GraalVM's native-image extension
        run: gu install native-image

      - uses: actions/download-artifact@v2
        with:
          path: ./

      - name: Create native fcli
        run: mkdir -p native-image/mac && native-image ${{ env.native_image_opts }} -jar ./artifact/fcli.jar native-image/mac/fcli
       
      - name: Compress native fcli
        uses: svenstaro/upx-action@v2
        with:
          file: native-image/mac/fcli
        
      - name: Basic test of native fcli
        run: ./native-image/mac/fcli --help && ./native-image/mac/fcli get --help

      - uses: actions/upload-artifact@v2
        with:
          path: ./native-image

  release_win:
    name: native-image-win
    needs: build
    runs-on: windows-2019
    steps:
    - uses: DeLaGuardo/setup-graalvm@3
      with:
        graalvm-version: '21.2.0.java11'

    - name: Install GraalVM's native-image extension
      run: ${{ env.JAVA_HOME }}\bin\gu.cmd install native-image

    - uses: actions/download-artifact@v2
      with:
        path: ./

    - name: Create native fcli
      run: >-
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" &&
        mkdir native-image\win &&
        ${{ env.JAVA_HOME }}\bin\native-image.cmd ${{ env.native_image_opts }} -jar .\artifact\fcli.jar native-image\win\fcli
      shell: cmd

      
    - name: Compress native fcli
      uses: svenstaro/upx-action@v2
      with:
        file: native-image\win\fcli.exe
      

    - name: Basic test of native fcli
      run: |
        .\native-image\win\fcli.exe --help 
        .\native-image\win\fcli.exe get --help

    - uses: actions/upload-artifact@v2
      with:
        path: ./native-image
